name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - run: sudo apt-get install gcc-riscv64-unknown-elf
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --release --verbose
      - run: cargo run --release --verbose
      # ensure recompile
      - run: touch riscv-instruction/src/lib.rs
      - run: cargo test --release --verbose -- --show-output
